---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-coredns
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - to:
      - podSelector:
          matchLabels:
            k8s-app: kube-dns
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-whoami
spec:
  podSelector:
    matchLabels:
      app: whoami-ng
  policyTypes:
    - Ingress
